language: node_js
node_js:
- '0.10'
env:
  global:
  - GH_REF: github.com/bem/bem-components.git
  - ISTANBUL_COVERAGE: true
  matrix:
  - TEST_SCOPE: lint
  - TEST_SCOPE: specs
  - TEST_SCOPE: gemini
matrix:
  fast_finish: true
branches:
  except:
  - v1
  - master
before_script:
- |
  if [ "${TEST_SCOPE}" == "gemini" ]; then
    sudo apt-get update -qq
    sudo apt-get install -qq -y graphicsmagick
    echo "capabilities:" >> .gemini.yml
    echo "  tunnel-identifier: '${TRAVIS_JOB_NUMBER}'" >> .gemini.yml
    echo "  build: '${TRAVIS_BUILD_NUMBER}'" >> .gemini.yml
    echo "  tags:" >> .gemini.yml
    echo "    - CI" >> .gemini.yml
    cat .gemini.yml
  fi
after_success:
- |
  if [ "${TEST_SCOPE}" == "specs" ]; then
    npm install coveralls
    node_modules/.bin/istanbul report lcovonly
    cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js && echo "Coverage data was sent to coveralls!"
  fi
addons:
  sauce_connect:
    username: SevInf
    access_key:
      secure: JNQwYZS6U6bC4gSg9C4lS8XCCTc5IqccwQ2JxLfE0mhXLk66uFOIGOl1wpWKu+B7Tqt71HRiHpVz8nuQTOehewLDrr3QOclnDN1t0QVi1n50FG/h2q8X4S1blw0+rwQycyJcWdCnnuoMbprdBOfxMirCaCQdppxA393OKOplmkc=
